### ISSUE TITLE
Documentation of how `StreamConsumer` is initialized

### ISSUE THREAD

**Issue by mooreniemi** [yuhao-su/aws-msk-iam-sasl-signer-rs#3]
I found it unintuitive that the code inside the `assert` was actually "load bearing" and `fetch_metadata` doesn't work without it. Could we document the example with an explanation?

https://github.com/yuhao-su/aws-msk-iam-sasl-signer-rs/blob/82eb8529e3a9653cff0f3c881934a67b3d144998/examples/consumer.rs#L70-L82

**Comment by yuhao-su** [comment]
Hi @mooreniemi , thank you for the feedback. I am creating a PR to address this issue.
